# I think this values are right
# but has not been tested in all android architectures

# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# ALIGNOF_INT64_T
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set ALIGNOF_INT64_T to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The COMPILE_RESULT variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/builder/.termux-build/swi-prolog/build/CMakeFiles/CMakeTmp/c_get_ALIGNOF_INT64_T_alignment.c
# Executable    : /home/builder/.termux-build/swi-prolog/build/CMakeFiles/cmTC_e7e1a-ALIGNOF_INT64_T
# Run arguments : 
#    Called from: [3]	/home/builder/.termux-build/swi-prolog/src/cmake/AlignOf.cmake
#                 [2]	/home/builder/.termux-build/swi-prolog/src/cmake/Config.cmake
#                 [1]	/home/builder/.termux-build/swi-prolog/src/src/CMakeLists.txt

set( ALIGNOF_INT64_T 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)


# ALIGNOF_DOUBLE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set ALIGNOF_DOUBLE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The COMPILE_RESULT variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/builder/.termux-build/swi-prolog/build/CMakeFiles/CMakeTmp/c_get_ALIGNOF_DOUBLE_alignment.c
# Executable    : /home/builder/.termux-build/swi-prolog/build/CMakeFiles/cmTC_297f0-ALIGNOF_DOUBLE
# Run arguments : 
#    Called from: [3]	/home/builder/.termux-build/swi-prolog/src/cmake/AlignOf.cmake
#                 [2]	/home/builder/.termux-build/swi-prolog/src/cmake/Config.cmake
#                 [1]	/home/builder/.termux-build/swi-prolog/src/src/CMakeLists.txt

set( ALIGNOF_DOUBLE 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)


# ALIGNOF_VOIDP
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set ALIGNOF_VOIDP to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The COMPILE_RESULT variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/builder/.termux-build/swi-prolog/build/CMakeFiles/CMakeTmp/c_get_ALIGNOF_VOIDP_alignment.c
# Executable    : /home/builder/.termux-build/swi-prolog/build/CMakeFiles/cmTC_c5fa7-ALIGNOF_VOIDP
# Run arguments : 
#    Called from: [3]	/home/builder/.termux-build/swi-prolog/src/cmake/AlignOf.cmake
#                 [2]	/home/builder/.termux-build/swi-prolog/src/cmake/Config.cmake
#                 [1]	/home/builder/.termux-build/swi-prolog/src/src/CMakeLists.txt

set( ALIGNOF_VOIDP 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

